addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.7.1")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.2.21" )
addSbtPlugin("org.scalameta" % "sbt-native-image" % "0.3.0")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.9")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.7.0")
