name: learn-github-actions
on: [pull-request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jdk: [graalvm@22.1.0]
    name: Test ${{ matrix.os }} -- ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: olafurpg/setup-scala@v12
        with:
          java-version: ${{ matrix.jdk }}

      - name: native-image
        run: 'sbt ''run run -- nativeImage'''
        shell: bash

      - name: run-native-image
        run: ./bin/buildsonnet run -- nativeImage
        shell: bash
