name: scalafmt
on:
  pull_request:
    branches:    
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: scalafmt
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1
        with:
          apps: scalafmt

      - name: test-scalafmt
        run: scalafmt --test --mode anygit
        shell: bash
